### ISSUE TITLE
SOS GetFeatureOfInterest incorrectly attempts to cast features to AbstractFeature in v2

### ISSUE THREAD

**Issue by csdillard** [opensensorhub/osh-core#182]
If you implement `IGeoFeature` directly in your sensor, then request XML/GML features of interest from your node, the SOS throws an exception:

```
java.lang.ClassCastException: class xxxxxxxx cannot be cast to class net.opengis.gml.v32.AbstractFeature 
	at NativeClassLoader//org.sensorhub.impl.service.sos.FeatureSerializerGml.writeRecord(FeatureSerializerGml.java:111)
	at NativeClassLoader//org.sensorhub.impl.service.sos.FeatureSerializerGml.writeRecord(FeatureSerializerGml.java:45)
	at NativeClassLoader//org.sensorhub.impl.service.sos.AbstractAsyncSerializer.onWritePossible(AbstractAsyncSerializer.java:127)
	at NativeClassLoader//org.sensorhub.impl.service.sos.AbstractAsyncSerializer.onNext(AbstractAsyncSerializer.java:155)
```

(Class name is redacted with `xxxxxxxx`.)

Note that the JSON serializer works just fine.

**Comment by alexrobin** [comment]
Should be fixed with f591d03 in branch v2.
