### ISSUE TITLE
FileUtils.isSafeFilePath() throws internal error when FileSeparator is backslash character

### ISSUE THREAD

**Issue by TheRestOfMe** [opensensorhub/osh-core#37]
Error occurs on line 73:  
`String[] parts = path.split(File.separator);`

To reproduce, run the unit test in Windows environment.  Exception occurs:

Exception in thread "main" java.util.regex.PatternSyntaxException: Unexpected internal error near index 
\
 ^
    at java.util.regex.Pattern.error(Pattern.java:1924)
    at java.util.regex.Pattern.compile(Pattern.java:1671)
    at java.util.regex.Pattern.<init>(Pattern.java:1337)
    at java.util.regex.Pattern.compile(Pattern.java:1022)

This is due to '\' character having specific meaning in regex.  A simple fix is to test the File.separator String and force it to `"\\\\"`if it is `"\\"` .  

```
 public static boolean isSafeFilePath(String path)
    {
        if (path == null)
            return false;

        Pattern regex = Pattern.compile("[" + ALLOWED_FILE_CHARS + "]*");
        String s = File.separator.equals("\\") ?  "\\\\" : File.separator;
        String[] parts = path.split(s);
```

**Comment by alexrobin** [comment]
Fixed in 1.1.0
