### ISSUE TITLE
Interconnecting Sensor

### ISSUE THREAD

**Issue by josephwinston** [opensensorhub/osh-core#43]
I'm having trouble building interconnecting sensors.  I'm attempting to following the [Pull Approach](http://docs.opensensorhub.org/user/sos/interconnect/).  By the way, if this should be opened in the documentation repo let me know.

The first image shows OpenSensorHub running on my local machine with the service on port 8383.  This instance is in its own directory. I am attempting to attach to the *Simulated Weather Sensor 3* 

![sensor3](https://cloud.githubusercontent.com/assets/226217/20271113/540eeec2-aa4f-11e6-8b7b-200407f883d9.png)

The next image shows OpenSensorHub running on the same local machine on port 818.  As before, this instance is in its own directory.

![virtual](https://cloud.githubusercontent.com/assets/226217/20271245/c9ef6306-aa4f-11e6-8e00-5d604639a049.PNG)

When I attempt to start the sensor, the following traceback is generated:

```
2016-11-14 09:49:38.470 [ModuleRegistry-43] INFO  SWEVirtualSensor:41b6e74b - Module STARTING
2016-11-14 09:49:38.471 [EventBus-402] INFO  ModuleRegistry - Starting module 'New SWE Virtual Sensor' [03615b4f-2a64-4f4e-a496-f911
f7ecfe18]
2016-11-14 09:49:38.484 [ModuleRegistry-43] ERROR SWEVirtualSensor:41b6e74b - Error while starting module
org.sensorhub.api.common.SensorHubException: Requested observation data is not available from SOS http://localhost:8383/sensorhub/so
s. Check Sensor UID and observed properties have valid values.
        at org.sensorhub.impl.sensor.swe.SWEVirtualSensor.start(SWEVirtualSensor.java:166) ~[sensorhub-service-swe-1.1.0.jar:na]
        at org.sensorhub.impl.module.AbstractModule.requestStart(AbstractModule.java:448) ~[sensorhub-core-1.1.0.jar:na]
        at org.sensorhub.impl.module.ModuleRegistry$2.run(ModuleRegistry.java:497) [sensorhub-core-1.1.0.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_102]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
2016-11-14 09:49:38.484 [ModuleRegistry-43] INFO  SWEVirtualSensor:41b6e74b - Module STOPPING
2016-11-14 09:49:38.484 [ModuleRegistry-43] INFO  SWEVirtualSensor:41b6e74b - Module STOPPED
```

How do I either adjust what I am doing or provide enough information to troubleshoot this issue?

**Comment by josephwinston** [comment]
Close.  The issues were

*  The Sensor UID is the ```swes:procedure``` value.  In the example above based on the default deployment it is ```urn:osh:sensor:simweather:0123456879```
* The observation comes from one of the ```swes:observableProperty``` entries.  For example <http://sensorml.com/ont/swe/property/Weather>
